name: Elm CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Check that Elm code compiles!
        run: elm make src/Main.elm
      - name: Run elm-review
        run: yarn review
